version: "3.9"

services:
  registry-frontend:
    build: ./registry-frontend
    image: 936184503418.dkr.ecr.us-east-2.amazonaws.com/registry-frontend:latest
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      VUE_APP_REGISTRY_BACKEND_URL: http://ec2-18-217-245-42.us-east-2.compute.amazonaws.com:3000/
  registry-backend:
    build: ./registry-backend
    image: 936184503418.dkr.ecr.us-east-2.amazonaws.com/registry-backend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./database:/database
    environment:
      NODE_ENV: production
      DATABASE_DIR: /database/
      API_KEY: CS4471Group6
