version: "3.9"

services:
  registry-frontend:
    build: .
    image: registry-frontend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: production
  registry-backend:
    build: .
    image: registry-backend
    ports:
      - "3000:3000"
    volumes:
      - ./database:/database
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_DIR: /database/
      API_KEY: CS4471Group6
