version: "3.9"

services:
  registry-frontend:
    build: ./registry-frontend
    image: registry-frontend
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
  registry-backend:
    build: ./registry-backend
    image: registry-backend
    ports:
      - "3000:3000"
    volumes:
      - ./database:/database
    environment:
      NODE_ENV: production
      DATABASE_DIR: /database/
      API_KEY: CS4471Group6
