version: '3.9'

services:
  stock_comparison_frontend:
    container_name: stock_comparison_frontend_container
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true